# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_id', models.CharField(max_length=200)),
                ('commit_title', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('url', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('status', models.CharField(default='A', max_length=1)),
                ('created_by', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=100)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(to='control.User')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=200)),
                ('reviewer', models.CharField(max_length=100)),
                ('review_time', models.DateTimeField()),
                ('review', models.TextField()),
                ('usefulness', models.CharField(max_length=1)),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Commit')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Project')),
            ],
        ),
        migrations.AddField(
            model_name='commit',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Project'),
        ),
    ]
